# This file is designed for local hosting and development work
services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal_network
      - external_network

  db:
    restart: always
    image: postgres:14-alpine
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - .dev/postgres14:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - .dev/redis:/data

  migrations:
    image: tootsuite/mastodon:v4.5.7
    env_file: .env.mastodon
    command: rake db:prepare && rake db:migrate
    depends_on:
      db:
        condition: service_started
    networks:
      - external_network
      - internal_network

  web:
    image: tootsuite/mastodon:v4.5.7
    restart: always
    env_file: .env.mastodon
    command: bundle exec puma -C config/puma.rb
    networks:
      - external_network
      - internal_network
    ports:
      - '3001:3000'
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    volumes:
      - .dev/public/system:/mastodon/public/system

  streaming:
    image: ghcr.io/mastodon/mastodon-streaming:v4.5.7
    env_file: .env.mastodon
    command: node ./streaming/index.js
    networks:
      - external_network
      - internal_network
    ports:
      - '4000:4000'
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      migrations:
        condition: service_completed_successfully

  sidekiq:
    image: tootsuite/mastodon:v4.5.7
    restart: always
    env_file: .env.mastodon
    command: bundle exec sidekiq
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    networks:
      - external_network
      - internal_network
    volumes:
      - .dev/public/system:/mastodon/public/system
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 8' || false"]

networks:
  external_network:
  internal_network:
    internal: true

volumes:
  caddy_data:
  caddy_config:
