# https://taskfile.dev

version: "3"
dotenv: ['.env.development']
tasks:
  build:
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/event.proto
  sources:
    - proto/*.proto
  generates:
    - proto/*.pb.go

  dev:spin:
    cmds:
      - task dev:down
      - sleep 1
      - docker-compose up -d

  dev:down:
    cmds:
      - docker-compose down
  
  pub-sub:up:
    deps: [build]
    cmds:
      - go run ./pub-sub/main.go

  api:up:
    deps: [build]
    cmds:
      - go run ./api/*.go

  backend:up:
    deps: [build]
    cmds:
      - task pub-sub:up api:up -p

  default:
    cmds:
    - task backend:up
